name: Build

on:
  release:
    types:
      - released

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Build the docker image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,enable=true,priority=200,prefix=v,value=${{ steps.get-latest-tag.outputs.tag }}

      - name: Build and push App image
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.get-latest-tag.outputs.tag }}
          cache-to: type=inline
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.get-latest-tag.outputs.tag }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
